name: CreatePR call

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: imageTag
        required: true
        type: string
        default: "0.110.13"
      target_repository:
        description: target_repo
        required: true
        type: string
        default: "auroaj/sec"
      configType:
        description: configType
        required: true
        type: string
        default: "cm"
      configmap_prop:
        description: configmap_prop
        required: false
        type: string
        default: 'data."values.yaml"'
      yaml_prop:
        description: yaml_prop
        required: true
        type: string
        default: "app.imageTag"
      github_event_url:
        description: github.event.pull_request.html_url
        required: false
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up runner
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.head_ref.replace(/\//g, "_") }}

  call-build-dev:
    if: ${{ inputs.configType == 'cm' }}
    uses: ./.github/workflows/create_pr.yml
    with:
      target_repository: ${{ github.event.inputs.target_repository }}
      configFile: "2-app-workflows-cm.yaml"
      imageTag: ${{ github.event.inputs.imageTag }}
      configType: ${{ github.event.inputs.configType }}
      configmap_prop: ${{ github.event.inputs.configmap_prop }}
      yaml_prop: ${{ github.event.inputs.yaml_prop }}
      title: "ConfigMap argocd"
      github_event_url: ${{ github.event.pull_request.html_url }}
    secrets:
      GIT_ACTION_PAT: ${{ secrets.GIT_ACTION_PAT }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  call-build-yaml:
    if: ${{ inputs.configType == 'yaml' }}
    uses: ./.github/workflows/create_pr.yml
    with:
      target_repository: ${{ github.event.inputs.target_repository }}
      configFile: "values.yaml"
      imageTag: ${{ github.event.inputs.imageTag }}
      configType: "yaml"
      yaml_prop: ${{ github.event.inputs.yaml_prop }}
      github_event_url: ${{ github.event.pull_request.html_url }}
      title: "Wordpress values.yaml"
    secrets:
      GIT_ACTION_PAT: ${{ secrets.GIT_ACTION_PAT }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
