name: Build Trigger Container

on:
  push:
    branches:
      - main
    paths:
      - "amp/**"
      - ".github/workflows/build-amp-container.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "amp/**"
      - ".github/workflows/build-amp-container.yaml"

  workflow_run:
    workflows:
      - "Build base Container"
    types:
      - "completed"



jobs:
  check-if:
    outputs:
      head_sha_base: ${{ steps.check.outputs.head_sha_base }}
    runs-on: ubuntu-latest
    steps:
      - name: check
        id: check
        run: |
          export head_sha_base=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/auroaj/actions/actions/runs?status=in_progress \
          jq '.workflow_runs[] | select(.name == "Build base Container").head_sha')

          echo "::set-output name=head_sha_base::${head_sha_base}"
          echo ${{ github.sha }}
          echo ${{ head_sha_base }}

  push:
    if: ${{ needs.check-if.outputs.head_sha_base != github.sha }}
    runs-on: ubuntu-latest
    needs: check-if

    steps:
      - name: Test echo
        run: |
          echo "build trigger"
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}

