name: Build Trigger Container

on:
  push:
    branches:
      - main
    paths:
      - "amp/**"
      - ".github/workflows/build-amp-container.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "amp/**"
      - ".github/workflows/build-amp-container.yaml"

  workflow_run:
    workflows:
      - "Build base Container"
    type:
      - "completed"
      - "complete"



jobs:
  push:
    if: ${{ (github.event_name == 'workflow_run' && github.event.action == 'completed') || github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Test echo
        run: |
          echo "build trigger"
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}

