name: Build Trigger Container

on:
  push:
    branches:
      - main
    paths:
      - "amp/**"
      - ".github/workflows/build-amp-container.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "amp/**"
      - ".github/workflows/build-amp-container.yaml"

  workflow_run:
    workflows:
      - "Build base Container"
    types:
      - "completed"



jobs:
  check-if:
    outputs:
      skip_build: ${{ steps.check.outputs.skip_build }}
    runs-on: ubuntu-latest
    steps:
      - name: Clean up runner
        run: |
          rm -f ~/.ssh/*
          rm -f ~/.gitconfig
        continue-on-error: true
      - name: Clean Workspace
        uses: AutoModality/action-clean@d004b47eb728f2a83316fc70ba9a62ef97278013 # v1.1.0
      - name: Checkout Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Get Changes
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'

      - name: check
        id: check
        run: |
          echo "${{ steps.files.outputs.all }}" | grep "base/" && export skip_build="true" || true
          echo ${skip_build}
          echo "::set-output name=skip_build::${skip_build}"

  push:
    if: ${{ needs.check.outputs.skip_build != true }}
    runs-on: ubuntu-latest
    needs: check-if

    steps:
      - name: Test echo
        run: |
          echo "build trigger"
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}

