name: CreatePR call

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true
        type: string
        default: "0.110.13"
      target_repository:
        description: target_repo
        required: true
        type: string
        default: "auroaj/sec"
      github_event_name:
        description: github.event_name
        required: false
        type: string
        default: 'push'


jobs:
  call-build-dev:
    uses: ./.github/workflows/create_pr.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      target_repository: ${{ github.event.inputs.target_repository }}
      # pathValues: "values.yaml"
      pathValues: "2-app-workflows-cm.yaml"
      stringToSearch: "imageTag"

      github_event_name: ${{ github.event_name }}
    secrets:
      GIT_ACTION_PAT: ${{ secrets.GIT_ACTION_PAT }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
