name: CreatePR reuse

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string
      target_repository:
        required: true
        type: string
      configType:
        required: true
        type: string
      configmap_prop:
        required: false
        type: string
      yaml_prop:
        required: true
        type: string
      configFile:
        required: true
        type: string
      # stringToSearch:
      #   required: true
      #   type: string
      github_event_name:
        required: true
        type: string

    secrets:
      GIT_ACTION_PAT:
        required: true
      GCP_SA_KEY:
        required: true

env:
  environment: ${{ inputs.environment }}
  github_event_name: ${{ inputs.github_event_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      with:
        token: ${{ secrets.GIT_ACTION_PAT }}
        repository: ${{ inputs.target_repository }}
        path: target_repo

    - name: Update image version in ConfigMap
      uses: mikefarah/yq@v4.25.2
      # working-directory: target_repo
      # run: |
          # VERSION=v4.25.0
          # BINARY=yq_linux_amd64
          # wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq &&\
          # chmod +x /usr/bin/yq
          # yq ".$CM_PROP" ${{ inputs.configFile }} > data.tmp
          # yq -i '.'$Y_PROP' = "${{ inputs.imageTag }}\"' data.tmp
      with:
        cmd: |
          cd target_repo
          ls -la
          CM_PROP='${{ inputs.configmap_prop }}'
          Y_PROP='${{ inputs.yaml_prop }}'

          yq '.${{ inputs.configmap_prop }}' ${{ inputs.configFile }} > data.tmp
          yq -i '.${{ inputs.yaml_prop }} = "${{ inputs.imageTag }}"' data.tmp
          DATA=$(cat data.tmp) yq -i '.${{ inputs.configmap_prop }} = strenv(DATA)' ${{ inputs.configFile }}
          rm data.tmp

    # - name: Update Image Version in the related HelmChart values.yaml
    #   uses: fjogeleit/yaml-update-action@v0.10.0
    #   with:
    #     valueFile: ${{ inputs.configFile }}
    #     propertyPath: "data['values.yaml'].app.imageTag"
    #     value: ${{ inputs.imageTag }}
    #     repository: ${{ inputs.target_repository }}
    #     branch: create_pr/${{ inputs.imageTag }}
    #     targetBranch: master
    #     createPR: true
    #     labels: 'imageimageTag-update'
    #     message: 'Update Image Version to ${{ inputs.imageTag }}'
    #     token: ${{ secrets.GIT_ACTION_PAT }}
    #     workDir: target_repo

    - name: Commit changes
      env:
        imageTag: ${{ inputs.imageTag }}
        configFile: ${{ inputs.configFile }}
        # stringToSearch: "${{ inputs.stringToSearch }}"
      working-directory: target_repo
      run: |
        git config user.name '${{ github.actor }}'
        git config user.email '${{ github.actor }}@users.noreply.github.com'
        # set -x
        # sed -i 's/'${stringToSearch}': .*$/'${stringToSearch}': '${imageTag}'/1' ${configFile}
        git add -A
        git commit -m "updated version in ${configFile}"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27 # v4.0.4
      with:
        path: target_repo
        token: ${{ secrets.GIT_ACTION_PAT }}
        commit-message: Update imageTag
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        # branch: example-patches
        # delete-branch: true
        title: '[Auto] Update imageTag'
        body: |
          Update imageTag
          #TODO Link to original commit/pr
        # assignees: peter-evans
        # reviewers: peter-evans
        # team-reviewers: |
        #   owners
        #   maintainers
        draft: false
