name: test tagging

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

env:
  docker_image_amp: us-docker.pkg.dev/shared-buckets-333815/amp/k8s-amp
  ols_version: "1.7.15"
  php_version: "7.4.28"
  wp_version: "5.9.2"
  wp_sha1: "19653440effafce0f768a1ba5092710717835bdc"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GIT_ACTION_PAT }}
          tag_prefix: "amp_v"

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GIT_ACTION_PAT }}

      - name: Get the changelog
        run: |
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTION_PAT }}
        with:
          tag_name: ${{steps.tag_version.outputs.new_tag }}
          release_name: ${{steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false